server:
  name: violin-notice
  addr: "0.0.0.0:80"

zap:
  debugFileName: "/log/notice/debug.log"
  infoFileName: "/log/notice/info.log"
  warnFileName: "/log/notice/warn.log"
  maxSize: 500
  maxAge: 28
  maxBackups: 3

redis:
  host: "localhost"
  port: 6379
  password: "123456"
  db: 3

grpc:
  name: notice-service
  addr: "0.0.0.0:8081"
