// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: reminder_service.proto

package notice_service_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NoticeMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NoticeMessage) Reset() {
	*x = NoticeMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notice_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoticeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoticeMessage) ProtoMessage() {}

func (x *NoticeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_notice_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoticeMessage.ProtoReflect.Descriptor instead.
func (*NoticeMessage) Descriptor() ([]byte, []int) {
	return file_notice_service_proto_rawDescGZIP(), []int{0}
}

type NoticeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NoticeResponse) Reset() {
	*x = NoticeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notice_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoticeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoticeResponse) ProtoMessage() {}

func (x *NoticeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notice_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoticeResponse.ProtoReflect.Descriptor instead.
func (*NoticeResponse) Descriptor() ([]byte, []int) {
	return file_notice_service_proto_rawDescGZIP(), []int{1}
}

var File_notice_service_proto protoreflect.FileDescriptor

var file_notice_service_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x6e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x22, 0x0f, 0x0a, 0x0d, 0x4e, 0x6f, 0x74,
	0x69, 0x63, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x10, 0x0a, 0x0e, 0x4e, 0x6f,
	0x74, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x64, 0x0a, 0x0d,
	0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x53, 0x0a,
	0x0a, 0x53, 0x65, 0x6e, 0x64, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x12, 0x20, 0x2e, 0x6e, 0x6f,
	0x74, 0x69, 0x63, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x21, 0x2e,
	0x6e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x2d, 0x5a, 0x2b, 0x76, 0x69, 0x6f, 0x6c, 0x69, 0x6e, 0x2d, 0x6e, 0x6f, 0x74,
	0x69, 0x63, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f,
	0x6e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_notice_service_proto_rawDescOnce sync.Once
	file_notice_service_proto_rawDescData = file_notice_service_proto_rawDesc
)

func file_notice_service_proto_rawDescGZIP() []byte {
	file_notice_service_proto_rawDescOnce.Do(func() {
		file_notice_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_notice_service_proto_rawDescData)
	})
	return file_notice_service_proto_rawDescData
}

var file_notice_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_notice_service_proto_goTypes = []interface{}{
	(*NoticeMessage)(nil),  // 0: notice.service.v1.NoticeMessage
	(*NoticeResponse)(nil), // 1: notice.service.v1.NoticeResponse
}
var file_notice_service_proto_depIdxs = []int32{
	0, // 0: notice.service.v1.NoticeService.SendNotice:input_type -> notice.service.v1.NoticeMessage
	1, // 1: notice.service.v1.NoticeService.SendNotice:output_type -> notice.service.v1.NoticeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_notice_service_proto_init() }
func file_notice_service_proto_init() {
	if File_notice_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_notice_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoticeMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notice_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoticeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_notice_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notice_service_proto_goTypes,
		DependencyIndexes: file_notice_service_proto_depIdxs,
		MessageInfos:      file_notice_service_proto_msgTypes,
	}.Build()
	File_notice_service_proto = out.File
	file_notice_service_proto_rawDesc = nil
	file_notice_service_proto_goTypes = nil
	file_notice_service_proto_depIdxs = nil
}
